export const ALIAS_TITLES = [
  "Agent",
  "Analyst",
  "Archivist",
  "Barrister",
  "Captain",
  "Constable",
  "Citizen",
  "Commander",
  "Courier",
  "Detective",
  "Director",
  "Doctor",
  "Engineer",
  "Inspector",
  "Investigator",
  "Magistrate",
  "Mr.",
  "Mrs.",
  "Mx.",
  "Operative",
  "Professor",
  "Scholar",
  "Sir",
  "Dame",
  "Solicitor",
  "Strategist",
  "Technician",
  "Warden",
];

export const ALIAS_COLORS = [
  "Onyx",
  "Umber",
  "Scarlet",
  "Amber",
  "Gold",
  "Emerald",
  "Azure",
  "Violet",
  "Rose",
  "Ivory",
];

export const ALIAS_COLOR_HEX: Record<string, string> = {
  Onyx: "#1f1f1f",
  Umber: "#7a4f32",
  Scarlet: "#c1121f",
  Amber: "#d97706",
  Gold: "#b8860b",
  Emerald: "#047857",
  Azure: "#2563eb",
  Violet: "#7c3aed",
  Rose: "#e11d48",
  Ivory: "#bda788",
};

export const IDENTITIES = [
  "The Murderer",
  "The Great Detective",
  "The Mastermind",
  "The Time Traveler",
  "The Jewel Thief",
  "The Wizard",
  "The Master Spy",
  "The Actor",
  "The Royal",
  "The Bureaucrat",
];

export const WEAPONS = [
  "Candlestick",
  "Dagger",
  "Letter Opener",
  "Poison Vial",
  "Revolver",
  "Rope",
  "Wrench",
  "Scalpel",
  "Fire Poker",
  "Paperweight",
];

export const LOCATIONS = [
  "Billiard Room",
  "Study",
  "Ballroom",
  "Conservatory",
  "Library",
  "Gallery",
  "Courtyard",
  "Observatory",
  "Boathouse",
  "Servant Quarters",
];

export const MOTIVES = [
  "Ambition",
  "Blackmail",
  "Jealousy",
  "Revenge",
  "Inheritance",
  "Cover-up",
  "Obsession",
  "Debt",
  "Rivalry",
  "Silencing Witness",
];
